services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: merebdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mereb_app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 20s

  user-service:
    image: leultewolde/user-service:latest
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/merebdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      CORS_ALLOWED_ORIGINS: http://localhost:8084,http://localhost:5173,http://192.168.1.109:8085,http://mereb-web:80
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mereb_app-network

  post-service:
    image: leultewolde/post-service:latest
    build:
      context: ./post-service
      dockerfile: Dockerfile
    container_name: post-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/merebdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      USER_SERVICE_URL: user-service:8082
      CORS_ALLOWED_ORIGINS: http://localhost:8084,http://localhost:5173,http://192.168.1.109:8085,http://mereb-web:80
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mereb_app-network

  mereb-web:
    image: leultewolde/mereb-web:latest
    build:
      context: ./mereb-web
      dockerfile: Dockerfile
    container_name: mereb-web
    ports:
      - "8084:80"
    environment:
      NODE_ENV: production
      VITE_USER_SERVICE_URL: localhost:8082
      VITE_POST_SERVICE_URL: localhost:8083
    depends_on:
      user-service:
        condition: service_started
      post-service:
        condition: service_started
    networks:
      - mereb_app-network

volumes:
  postgres_data:


networks:
  mereb_app-network:
    driver: bridge
