services:
  # api-gateway:
  #   image: leultewolde/api-gateway:latest
  #   container_name: api-gateway
  #   build:
  #     context: ./api-gateway
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8084:8084"
  #   networks:
  #     - mereb_app-network

  user-service:
    image: leultewolde/user-service:latest
    container_name: user-service
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      CORS_ALLOWED_ORIGINS: http://localhost:8084,http://localhost:5173,http://192.168.1.109:8085,https://mereb.app
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - mereb_app-network

  post-service:
    image: leultewolde/post-service:latest
    container_name: post-service
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:
      CORS_ALLOWED_ORIGINS: http://localhost:8084,http://localhost:5173,http://192.168.1.109:8085,https://mereb.app
      USER_SERVICE_GET_USER_URL: http://user-service:8082/api/v2/users
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - mereb_app-network

networks:
  mereb_app-network:
    driver: bridge
